### ISSUE TITLE
AM4510C Gateway

### ISSUE THREAD

**Issue by Cm-8** [FredBlo/node-red-contrib-myhome-bticino-v2#25]
Hi to all,
Is the Bticino Gateway AM4510C compatibile with this node?
If not, how I can test it?
Thanks

**Comment by FredBlo** [comment]
Hi @Cm-8 ,

The AM4510C seems to be part of a new product range (and thus gateway).
There is no documentation I found on how it can be connected.

I would be very surprised if it would keep using the -quite old- OpenWebNet protocol. Also because I read they planned to remove the gateway support for upcoming firmware version of MyHomeServer1... (which is the latest available gateway of the Legrand/BTicino MyHome product range...
You can always try installing the node and set your gateway IP address in the config node to see if it connects... but do not expect much from it...

Let us know...

**Comment by Cm-8** [comment]
Hi @FredBlo,
I noticed that the HomeAssistant software integrates the Bticino AM4510C gateway through the netatmo platform, would it be possible to replicate the mode?
https://www.home-assistant.io/integrations/bticino/

**Comment by FredBlo** [comment]
Hi @Cm-8 ,

It is certainly possible to add such a connector, but it is a brand new one which will have to have its own logic.
It is another node-set which has to be developed to work within node-red, but will not be an 'extension' of the Bticino one.
Have you checked / tries the existing nodes for netatmo on node-red, such as https://flows.nodered.org/node/node-red-contrib-netatmo ?
