### ISSUE TITLE
Reconnection error every minutes with mh201

### ISSUE THREAD

**Issue by marcob79** [FredBlo/node-red-contrib-myhome-bticino-v2#5]
I'm experiencing a loop (once every minutes more or less) of error with the connection with my MH201.
Here the related log from nodered

`20/5/2021, 13:36:16node: MH201
msg : string[140]
"gateway connection issue (Command not acknowledged (NACK) when already connected): last known state was 'connected', trying to re-connect..."
20/5/2021, 13:36:17node: MH201
msg : string[100]
"gateway connection : disconnected from host, last known state was 'connected'. Auto retry activated."
20/5/2021, 13:36:17node: MH201
msg : string[113]
"gateway connection issue (socket connection closed): last known state was 'disconnected', trying to re-connect..."`

**Comment by FredBlo** [comment]
It seems the gateway is refusing a command which, in monitoring mode, is probably the 'keep alive' call.
Is this enabled on the gateway config node (every 60 sec) ? If it is, try disabling to check whether this is a possible root cause

**Comment by marcob79** [comment]
Yes, that's seems root cause.
I set it to 0 and now I didn't get the error anymore.
Do you think it could be fine to leave it in this way?
Do you suggest to try to upgrade my mh201 firmware in case (if I will be
able to do that and if there is a newer firmware) and try to enable keep
alive again?

Thanks


Il ven 21 mag 2021, 14:26 FredBlo ***@***.***> ha scritto:

**Comment by FredBlo** [comment]
During my tests, I only had to enable keep alive in the F455. The other gateways I tested (MH202, MyHomeServer1 and F459) never closed the connection, so keep alive was not necessary.
However, if you have a *technical* network interruption, it is not always detected. In such a case, the keep alive tries to connect, it fails (since connection was lost, but unaware), and automatically reconnects.
So I would advice to let a keep alive once every 60 minutes just in case.

PS : if a new firmware exists for your MH201, I advice to upgrade. Bticino does not make many firmware updates... only when really necessary... so if there is one, enjoy it ;-)

I will check if there are other 'keep alive' commands which I could use for next version & keep you posted

**Comment by FredBlo** [comment]
Hi @marcob79,

Fyi, I just released v2.2.0 (which inludes support for scenario (CEN/CEN+) management).
I also included a **fix** to better manage **keep alive** which should allow you to enable it again without having the side-effect encountered before.

Let me know if it worked for you :-)

**Comment by FredBlo** [comment]
let's consider it's okay now...

**Comment by marcob79** [comment]
Hi, sorry for late feedback.
I checked with 2.2.1 and it is fine as you said.
Thanks

**Comment by FredBlo** [comment]
OK @marcob79 , tks for feedback !
